# you can use envsubst as the following to generate the final manifest
# export APP=myappname
# envsubst < .kubernates/manifest.yaml > manifest.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: $APP-deployment
    labels:
        app: $APP
spec:
    replicas: 1
    selector:
        matchLabels:
            app: $APP
    template:
        metadata:
            labels:
                app: $APP
        spec:
            containers:
                - name: $APP
                  image: $IMAGE
                  ports:
                      - containerPort: 80
