# image around 208 MB
# build step
FROM mhart/alpine-node:14 as build

WORKDIR build

COPY package.json .

RUN yarn

COPY . .

RUN yarn build

# application environment
FROM mhart/alpine-node:14

ARG PROJECT_NAME=/project

WORKDIR $PROJECT_NAME

COPY --from=build build $PROJECT_NAME

CMD ["node", "dist/src/index.js"]