# image around 126 MB
# build step
ARG IMAGE=mhart/alpine-node:16
FROM $IMAGE as build

COPY . build

RUN cd build && \
    yarn && \
    yarn build && \
    rm -rf node_modules && \
    yarn --prod

# application environment
FROM $IMAGE

ARG PROJECT_NAME=/project

WORKDIR $PROJECT_NAME

COPY --from=build build $PROJECT_NAME

CMD ["node", "dist/src/index.js"]